name: Test Workflow
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed 
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - closed
jobs:
  test-workflow-itself:
    name: Test workflow itself
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Action
        # we can give directory path that contains action.yaml or repo address in username/repository_name@version format
        # in our case it would be nashmaniac/create-issue-action@v1.0 where v1.0 is the version of action
        # for now we will give directory path. The directory must contain action.yaml
        uses: ./
        # pass user input as arguments
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          pull-request-body: ${{ github.event.pull_request.body }}
          copy-issues-labels: true # optional
