name: Workflow for testing this action
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  test-workflow:
    name: Test this workflow action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Action
        id: find-linked-issues
        # we can give directory path that contains action.yaml or repo address in username/repository_name@version format
        # in our case it would be nashmaniac/create-issue-action@v1.0 where v1.0 is the version of action
        # for now we will give directory path. The directory must contain action.yaml
        uses: ./
        # pass user input as arguments
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          pull-request-body: ${{ github.event.pull_request.body }}
          copy-issues-labels: true # optional
          
      - name: Echo output
        run: |
          echo "is-pull-request-linked-to-issues: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues }}"
          echo "linked-issues: ${{ steps.find-linked-issues.outputs.linked-issues }}"
          
      - name: Echo output when success
        if: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues == 'True' }}
        run: |
          echo "is-pull-request-linked-to-issues: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues }}"
          echo "linked-issues: ${{ steps.find-linked-issues.outputs.linked-issues }}"
          
      - name: Echo output when failure and exit
        if: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues == 'False' }}
        run: |
          echo "is-pull-request-linked-to-issues: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues }}"
          echo "linked-issues: ${{ steps.find-linked-issues.outputs.linked-issues }}"
          exit 1
